spring:
  application:
    name: business-wxUser
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件总的最大值
      max-file-size: 10MB # 单个文件的最大值


security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9081/oauth/token
      user-authorization-uri: http://localhost:9081/oauth/authorize
    resource:
      token-info-uri: http://localhost:9081/oauth/check_token

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.business.controller
  registry:
    address: nacos://127.0.0.1
    port: 8848
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    timeout: 5000

server:
  port: 9082

management:
  endpoints:
    web:
      exposure:
        include: "*"
